spring:
  application:
    name: client-grpc

grpc:
  client:
    crawling-grpc-server:
      address: 'static://127.0.0.1:50051'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
